openapi: 3.1.0
x-stoplight:
  id: 9taqtiwqef9e2
info:
  title: ShopAPI
  version: '1.0'
servers:
  - url: 'http://localhost'
paths:
  /products:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
      operationId: get-products
      description: Get all products
    post:
      summary: ''
      operationId: post-products
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      title: Product
      x-stoplight:
        id: zna02m1h4it27
      type: object
      properties:
        id:
          type: string
        '':
          type: string
        description:
          type: string
        price:
          type: integer
        currency:
          type: string
          enum:
            - EUR
            - USD
          maxLength: 3
          minLength: 3
